apiVersion: nais.io/v1
kind: Alert
metadata:
  name: meldepliktalerts
  namespace: meldekort
  labels:
    team: meldekort
spec:
  receivers:
    slack:
      channel: '#team-meldeplikt-alerts-dev'
  alerts:
    - alert: meldeplikt-app-nede
      # Sjekker alle applikasjoner i team namespace
      expr: kube_deployment_status_replicas_available{namespace="meldekort"} == 0
      for: 2m
      description: "App *{{ $labels.deployment }}\ er nede i namespace {{ $labels.namespace }}"
      action: "`kubectl describe pod -l app={{ $labels.deployment }} -n {{ $labels.namespace }}` for events, og `kubectl logs -l app={{ $labels.deployment }} -n {{ $labels.namespace }}` for logger."
