name: Deploy to dev
on:
  push:
    branches-ignore:
      - 'master'
    paths:
      - .github/workflows/deploy-dev.yaml
      - .nais/meldepliktalerts-dev.yaml
      - .nais/vars.yaml
      - .nais/alerts.yaml
      - .nais/alerts-fss.yaml
      - .nais/alerts-gcp.yaml
env:
  RESOURCE_FILE: .nais/meldepliktalerts-dev.yaml
  RESOURCE_FILE_FSS: .nais/meldepliktalerts-dev-fss.yaml
  RESOURCE_FILE_GCP: .nais/meldepliktalerts-dev-gcp.yaml
  VARS_FILE: .nais/vars.yaml

jobs:
  deploy_dev:
    name: Deploy alerts to dev-fss
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Append alerts
        run: |
          cat .nais/alerts.yaml >> ${{ env.RESOURCE_FILE }}
          cat ${{ env.RESOURCE_FILE }} .nais/alerts-fss.yaml > ${{ env.RESOURCE_FILE_FSS }}
          cat ${{ env.RESOURCE_FILE }} .nais/alerts-gcp.yaml > ${{ env.RESOURCE_FILE_GCP }}

      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: ${{ env.RESOURCE_FILE_FSS }}
          VARS: ${{ env.VARS_FILE }}
          PRINT_PAYLOAD: true

      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: ${{ env.RESOURCE_FILE_GCP }}
          VARS: ${{ env.VARS_FILE }}
          PRINT_PAYLOAD: true
