name: Deploy to dev-fss
on:
  push:
    branches:
      - '*'
      - '!master'
    paths:
      - .github/workflows/deploy-dev.yaml
      - .nais/meldepliktalerts-dev.yaml
      - .nais/vars.yaml
      - .nais/alerts.yaml
env:
  RESOURCE_FILE: .nais/meldepliktalerts-dev.yaml

jobs:
  deploy_dev:
    name: Deploy alerts til dev-fss
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Append alerts
#        run: |
#          cat .nais/alerts.yaml >> env.RESOURCE_FILE
#
      - name: Debug
        run: |
          ls -l
          echo $(cat env.RESOURCE_FILE)

      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/meldepliktalerts-dev.yaml
          VARS: .nais/vars.yaml
          PRINT_PAYLOAD: true

#      - name: Deploy to dev-gcp
#        uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: dev-gcp
#          RESOURCE: meldepliktalerts-dev.yaml
#          VARS: .nais/vars.yaml
