name: Deploy to dev-fss
on:
  push:
    branches:
      - '*'
      - '!master'
    paths:
      - .github/workflows/deploy-dev-fss.yaml
      - meldepliktalerts-dev-fss.yaml
jobs:
  deploy_dev:
    name: Deploy alerts til dev-fss
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: meldepliktalerts-dev-fss.yaml
