name: Deploy alerts to all environments
on:
  push:
    branches:
      - 'master'
    paths:
      - .github/workflows/deploy.yaml
      - .nais/meldeplikt-alerts.yaml
      - .nais/vars.yaml
      - .nais/alerts-common.yaml
      - .nais/alerts-fss.yaml
      - .nais/alerts-gcp.yaml
env:
  RESOURCE_FILE: .nais/meldeplikt-alerts.yaml
  RESOURCE_FILE_FSS: .nais/meldeplikt-alerts-prod-fss.yaml
  RESOURCE_FILE_GCP: .nais/meldeplikt-alerts-prod-gcp.yaml
  VARS_FILE: .nais/vars.yaml

jobs:
  deploy_dev:
    name: Deploy alerts to all environments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Append alerts
        run: |
          cat .nais/alerts-common.yaml >> ${{ env.RESOURCE_FILE }}
          cat ${{ env.RESOURCE_FILE }} .nais/alerts-fss.yaml > ${{ env.RESOURCE_FILE_FSS }}
          cat ${{ env.RESOURCE_FILE }} .nais/alerts-gcp.yaml > ${{ env.RESOURCE_FILE_GCP }}

#      - name: Deploy to dev-fss
#        uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: dev-fss
#          RESOURCE: ${{ env.RESOURCE_FILE_FSS }}
#          VARS: ${{ env.VARS_FILE }}
#          PRINT_PAYLOAD: true
#
#      - name: Deploy to dev-gcp
#        uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: dev-gcp
#          RESOURCE: ${{ env.RESOURCE_FILE_GCP }}
#          VARS: ${{ env.VARS_FILE }}
#          PRINT_PAYLOAD: true
#
#      - name: Deploy to prod-fss
#        uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-fss
#          RESOURCE: ${{ env.RESOURCE_FILE_FSS }}
#          VARS: ${{ env.VARS_FILE }}
#          PRINT_PAYLOAD: true
#
#      - name: Deploy to prod-gcp
#        uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-gcp
#          RESOURCE: ${{ env.RESOURCE_FILE_GCP }}
#          VARS: ${{ env.VARS_FILE }}
#          PRINT_PAYLOAD: true
